import java.util.ArrayList;

public class Room {
    private String hoteltype ;
    private String roomtype ;
    private int numberofRooms;
    private int minoccupancy;
    private int maxoccupancy;
    private double[] weekRates = new double[7];
    
    public Room( String HotelType, String RoomType, int NumberofRooms, int MinOccupancy,int MaxOccupancy, int[] weekRates) {
        this.hoteltype = HotelType ;
        this.roomtype = RoomType ;
        this.numberofRooms = NumberofRooms ;
        this.minoccupancy = MinOccupancy ;
        this.maxoccupancy = MaxOccupancy ;        
    }
    
    public double[] getweekRates() {
        return weekRates;
    }
    
    public String getHotelType() {
        return hoteltype;
    }
    
    public String getRoomType() {
        return roomtype;        
    }
    
    public int NumberofRooms() {
        return numberofRooms ;       
    }
    
    public int MinOccupancy() {
        return minoccupancy ;
    }
    
    public int MaxOccupancy() {
        return maxoccupancy ;
    }
    
}
